apiVersion: apps/v1
kind: Deployment
metadata:
  name: uc1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uc1
  template:
    metadata:
      labels:
        app: uc1
    spec:
      containers:
      - name: uc1-container
        image: uc1-image
        ports:
        - containerPort: 5001

---
apiVersion: v1
kind: Service
metadata:
  name: uc1-service
spec:
  selector:
    app: uc1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uc2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uc2
  template:
    metadata:
      labels:
        app: uc2
    spec:
      containers:
      - name: uc2-container
        image: uc2-image
        ports:
        - containerPort: 5002

---
apiVersion: v1
kind: Service
metadata:
  name: uc2-service
spec:
  selector:
    app: uc2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5002
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uc3-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uc3
  template:
    metadata:
      labels:
        app: uc3
    spec:
      containers:
      - name: uc3-container
        image: uc3-image
        ports:
        - containerPort: 5003

---
apiVersion: v1
kind: Service
metadata:
  name: uc3-service
spec:
  selector:
    app: uc3
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5003
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: frontend-image
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort